apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::588968403564:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-18ZJ664PO3AH7
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::588968403564:role/UdacityFlaskDeployCBKubectlRole
       username: build
       groups:
         - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-08T18:04:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "943"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 5688a3df-59b7-4352-9e6c-b039f5ade0d7
